# Generated by Django 4.0.5 on 2022-07-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='TDD',
            new_name='numeroID',
        ),
    ]
